---
title: "Module 1 Unstructured Writing Assignment"
description: |
  Includes summaries of and reactions to papers by Newell (1973) and Kolers and Roediger (1984)
author:
  - name: Liz Weglarz
    url: https://eweglarz3.github.io/Liz-Weglarz-PSY73800-Blog-Fall2021/
    affiliation: Baruch College
    affiliation_url: 
date: 09-08-2021
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```


# Module 1 Writing Assignment 

## Kolers, P. A., & Roediger, H. L. (1984). Procedures of mind.   Journal of Verbal Learning and Verbal Behavior,   23(4), 425–449.   <https://doi.org/10/b7gfkh>


**High-Level Summary:** Kolers & Roediger comment on the current psychological approach to studying information processes, which involves the acquisition, storage, and retrieval of information. Oftentimes, researchers have treated the mind and information as physical objects, but these authors are arguing for a process-oriented approach to information processing. As part of their argument, they highlight assumptions made within memory theories to refute some of the current approach, discuss the procedural approach and what it offers, and discuss the applications and extensions (e.g., potential) of this approach. 

**Reaction:** Kolers & Roediger write a very interesting and well developed argument for using a process-oriented approach to conceptualize learning and memory. The argument is rigorous, which makes the text a bit dense at times (although this is understandable if they were striving to make an argument for their case). 

**Detailed Summary of Key Points:** 

Assumptions about memory theories that have informed much of the contemporary research of memory and learning 

1. Spatial storage and search - this is supported by research that involves memory fading and posits that storage space for memories runs out at some point. 

2. Structure- process distinction - there is an assumption that the contents of information processing exist independently of information processing.

3. Use of mental structures - garners limited evidence, yet are over-relied upon and sometimes too simplistic to capture the process because everything in memory is connected 

4. Some sort of executive process coordinates all matters of the mind

5. Memory involves conscious recollection - when in reality, consciousness may be only of limited importance for recollection processes. 

6. Semantic primacy- meaning that researchers have over-indexed on the linguistic meaning of events and have assumed that all knowledge can be described in language (uses smells, knowledge of others is specific to the means of experiencing them)

**A procedural account of performance (refuting points above)** 

First, refutes many of the above assumptions by citing that:

- Many cog processes are well accommodate in procedural terms (3) 

- Semantics does not explain how sounds or smells can be remembered (6) 

- The familiarity of voice helps people to remember more, which refutes this point (2) 

- Operations of acquiring and recalling may differ and it affects perf (4) 

- Memorability is more of a u-shaped concept as opposed to something that fades away (1,5) 

**Evidence for Proceduralist View**

- Refutation of semantic primacy: cites evidence that it could not explain how we remember sounds, smells. Semantic also refers to the relation between a symbol and its referent. Semantic disparities refute its idea of primary as presenting worlds in a different orientation, learning by hearing and reading can generate different performance outcomes. 

- Means-dependent knowledge: process of attaining knowledge and the knowledge content cannot be wholly separated. Cites perceptuomotor functions like eye movements and motor skills as part of performance and knowledge acquisition methods that are consistent as being different. 

- Specificity of transfer: Cites evidence that those who were trained better perform better. Also refers to the importance of procedures used for positive training transfer. 

- Transfer vs. dissociation of skills: cites that dissociation is a natural state of affairs and its the characteristics of the tasks learned and the relations of underlying procedures used to learn they that need to be explained

- Consciousness: over-reliance on this is faulty because it assumes that one will always be able to describe what took place and it doesn’t actually aid in comprehension or performance 


**Applications and Extensions:** 

- For encoding phenomena includes levels of processing framework (procedures to acquire info does not translate to performance), generation effect (hearing vs. reading information renders diff performance outcomes), and the effect of imagery instructions on memory. 

- For interaction of acquisition and test includes citing the importance between procedural correspondence of learning and test circumstances and cites the source of knowledge as being important to performance, degree to which situation variables contextualize infor, or the resolution of problem solving. 
For recovery it includes the savings and transfer of training (which has faded from the mainstream view) adn the degree of transfer from one task to the next. 

**Reprise:** 

- There is a lack of cumulative process in information processing due to inappropriate farming of questions 

- This is due to assumptions in current approach 

- Argues that proceduralist approach can help to assuage these shortcomings 

- **Strengths of Proceduralist approach:** 

1. There is a unifying principle of behavior which is that complex skills can be broken down into simpler components 

2. Logic of transfer training can be used to identity component skills 

3. Procedural descriptions focus on observables 

- **Weaknesses of the Procedural Approach:** 

1. Imprecision of key statements and loose definition of terms such as skill and component, which are fundamental to the approach. 

2. There is a lack of a general definition, which makes it challenging to be positioned as a testable theory

- **Answers authors provide to assuage weaknesses:** 

- Skills are situation specific - so it is hard to draw general conclusions 
Theoretical procession- may times broadening model makes it hard to use or operate on 

- Testability - there is already a lot of evidence that supports the underlying notion of the procedural view (supports that notion that mentation is an activity and remembering is a skill) 

- Behavior is situation specific, but the description of behavior should have some generality 

Mind as construed in skill in manipulating symbols (recognition and problem solving) and applying them to new occasions (transfer) is a basis 

## Newell, A. (1973).   You can’t play 20 questions with nature and win: Projective comments on the papers of this symposium.   https://doi.org/10/gd4vz2 


**High-Level Summary:** Newell provides reaction and commentary within a review of a symposium. In a way, it feels as if Newell writes the start of the paper to illustrate how disconnected psychological research is to human behavior (writes it in third person, which feels disconnected). Newell offers an interesting critique of the research field in general, and summarizes the state of research as being incremental questions about the same topic (of which we never truly find an answer) or creating dichotomies to investigate further, and asks how these approaches will advance the field and change its reputation. With that, Newell offers an explanation as to why this may be the case, and cites our methods and lack of connection of research, and a lack of a control structure that can run all sorts of sequences to build out models and flows. Finally, Newell offers constructing complete models and analyzing complete tasks as being a way to solve for these shortcomings. 

**Reaction:** Newell provides a very colorful reaction to the symposium, and offers some pretty compelling arguments as to how the field needs to take new directions. As an I/O psychologist, my reactions were mostly to how this paper may have disrupted the psychological research community. This paper likely prompted a new discussion into the field that was very important, but has some shortcomings, and certainly is an opportunity for Newell to self-promote. Still, I think more about how this paper is relevant today. I am not entirely sure that we’ve overcome the complex of lacking as being a “mature science” (i.e., the replication crisis, etc.) so some of these approaches are still used. For me, there is a culture in the field that limits some of the suggestions that Newell provides, even today. The critique is largely aimed at the researchers, but there are industries that also uphold standard practices. Our methods and technologies have advanced, but I am not sure if those advances have done a whole lot to assuage Newell’s critiques. 

**Detailed Summary of Key Points:** 

**Detection** 

- Begins by discussing various sorts of psychological phenomena and its investigators and how the process of investigation generally goes. 

- Notes that it is important to continue to do research on these topics, and comments that there are other spaces that just continue to ask the same questions over and over again. 

- There is a construction of many oppositions (generally binary) to conceptualize and investigate these phenomena (“it's this way or it's that way”). 

- There are 2 constructs that drive current experimental style: 1) the discovery of empirical phenomena described earlier on, and 2) formulation of questions that center binary oppositions. Then, we generate experiments to support our explanations and then, this results in high level theory that feels detached from the day-to-day processes that scientists intend to explain. 

- This brings the question of how psychological science will advance. And will that involve using our same processes for more time, or finding new ones? And to what end? What is a mature science?

- With that, the questions that we want to answer become muddier over time, and clarity may not ever be reached. 

- Newell cites an article from Wingfield and Byrnes, that helps to clarify an aspect of a study of decay of information that was initially done about 20 years prior. While they answer 1 question unanswered there is still an issue that this process will continue on based on their unanswered questions. 

- Newel akins the scientific endeavor to playing a game of 20 questions. It starts with 1, and then it is broken down into every step, and the question is never actually answered. 

- In reviewing the symposium, Newell found it hard to tie them together. Looked at their underlying components, which further made them feel disconnected, and insignificant, and they will just be broken down and further analyzed. 

- Then comments on the papers. Commends their rigor, but comments that it misses a point and they all relate as they fall into a pattern of psychological activity that cannot cumulate.


**Diagnosis**

- Issues with methods: 

  - Researchers must know the method that a subject is using to perform an experimental task. But we’re totally engaged in the discovery and verification of specific methods used by subjects to do experimental tasks. 

  - Then, Newell talks about averaging over methods. We should find the structure that is fixed and variety so that we can infer the method. There will likely be a collection of methods to choose from, which leads to study design, and careful representation to understand post-hoc analysis, 

  - Then mentions advances in models, but comments that they lack a control structure- something that can safely specify the conditional sequence of processes without understanding all of the possibilities. Likens it to lacking a programming language. 

  - Some try to account for it by creating separate models, yet the control structure (likened to glue) is missing so there will be an indefinite sequence of alternative possibilities for how a given take was performed, which in turn leaves theoretical issues from being settled. 

- Putting it Together:

  - We lack results of all the experiments done put together. Comments on how we link previous research in our studies - often in intro or conclusion. 

  - Experimental results should not be permitted unless it can successfully challenge (or is consistent with) a substantial part of total existing patterns. 


**Prognosis:** 

- Newell argues we need to view humans as information processing systems. 

- First suggestion is to construct complete processing models as opposed to partial ones. One that includes human control processes ideally. 

  - Argues it is possible to construct models of detailed control structure with equally detailed assumptions about other processes happening. 
Each control organization has its own encoding, processing time, and memory  load. This provides a basis for analyzing many different tasks. 

- Second suggestion is to analyze a complete task. Current style is to design small experiments to settle small questions. Instead, experiments should focus on studies around a single complex task. 

  - This has not been done, and it is because no one has tried it. Gives examples of researchers who have begun to scratch the surface of this approach. 
- Third suggestion is to construct a single problem to perform many tasks. 





